docker exec -i postgres-db psql -U postgres -d postgres < 01-init.sql
docker exec -i postgres-db psql -U postgres -d postgres < 02-create_usuarios.sql
docker exec -i postgres-db psql -U postgres -d postgres < 03-create_autenticacion.sql
docker exec -i postgres-db psql -U postgres -d postgres < 04-create_busqueda.sql
docker exec -i postgres-db psql -U postgres -d postgres < 05-create_horarios.sql
docker exec -i postgres-db psql -U postgres -d postgres < 06-create_salas.sql
docker exec -i postgres-db psql -U postgres -d postgres < 07-create_reserva.sql
docker exec -i postgres-db psql -U postgres -d postgres < 08-create_pagos.sql
docker exec -i postgres-db psql -U postgres -d postgres < 09-create_notificaciones.sql
docker exec -i postgres-db psql -U postgres -d postgres < 10-create_validacion.sql
docker exec -i postgres-db psql -U postgres -d postgres < 11-create_promociones.sql